{% set name = "eodag" %}
{% set version = "2.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/eodag-{{ version }}.tar.gz
  sha256: a144d74c247fa3f67dd88acdd53484045912ade18b310094275cb6cee0912fa2

build:
  number: 0
  noarch: python
  entry_points:
    - eodag = eodag.cli:eodag
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - boto3
    - click
    - flasgger
    - flask >=1.0.2
    - geojson
    - jsonpath-ng
    - lxml
    - markdown >=3.0.1
    - owslib
    - pyproj
    - pyshp
    - pystac >= 1.0.0b1
    - python >=3.6
    - python-dateutil
    - pyyaml
    - requests
    - shapely
    - tqdm
    - usgs >=0.3.1
    - whoosh
    - ecmwf-api-cli

test:
  imports:
    - eodag
    - eodag.api
  commands:
    - pip check
    - eodag --help
  requires:
    - pip

about:
  home: https://github.com/CS-SI/eodag
  summary: Earth Observation Data Access Gateway
  license: Apache-2.0
  license_file: LICENSE
  description: |
    EODAG (Earth Observation Data Access Gateway) is a command line tool and a plugin-oriented Python
    framework for searching, aggregating results and downloading remote sensed images while offering
    a unified API for data access regardless of the data provider.
  doc_url: https://eodag.readthedocs.io
  dev_url: https://github.com/CS-SI/eodag

extra:
  recipe-maintainers:
    - maximlt
    - sbrunato
