{% set name = "eodag" %}
{% set version = "3.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/eodag-{{ version }}.tar.gz
  sha256: 311b393beffc1ca09e5fc4008e4d59f2e5608b860ec28d96a81754205bbd2fa9

build:
  number: 0
  entry_points:
    - eodag = eodag.cli:eodag

requirements:
  host:
    - python >=3.9

outputs:
  - name: eodag
    build:
      noarch: python
      script: python -m pip install . -vv
    requirements:
      host:
        - pip >=19.3
        - python {{ python_min }}
        - setuptools >=45
        - setuptools_scm >=6.2
      run:
        - annotated-types
        - boto3
        - botocore
        - click
        # Needed for PyJWT[crypto]
        - cryptography
        - ecmwf-api-client
        - geojson
        - jsonpath-ng
        - lxml
        - orjson
        - OWSLib >=0.27.1
        - pydantic >=2.1.0
        - pydantic-core
        - PyJWT >=2.5.0
        - pyproj >=2.1.0
        - pyshp
        - pystac >=1.0.0b1
        - python >={{ python_min }}
        - python-dateutil
        - PyYAML
        - requests
        - setuptools
        - shapely >=2.0.6
        - stream-zip
        - tqdm
        - typing_extensions >=4.8.0
        - urllib3
        - usgs >=0.3.1
        - Whoosh
    test:
      imports:
        - eodag
        - eodag.api
      commands:
        - pip check
        - eodag --help
      requires:
        - pip

  - name: eodag-server
    requirements:
      run:
        - {{ pin_subpackage('eodag', exact=True) }}
        - cachetools
        - fastapi >=0.93.0
        - pydantic-settings
        - python >=3.9
        - pygeofilter
        - starlette
        - uvicorn-standard
    test:
      imports:
        # dummy test; actual tests are in subpackages
        - eodag

about:
  home: https://github.com/CS-SI/eodag
  summary: Earth Observation Data Access Gateway
  license: Apache-2.0
  license_file: LICENSE
  description: |
    EODAG (Earth Observation Data Access Gateway) is a command line tool and a plugin-oriented Python
    framework for searching, aggregating results and downloading remote sensed images while offering
    a unified API for data access regardless of the data provider.
  doc_url: https://eodag.readthedocs.io
  dev_url: https://github.com/CS-SI/eodag

extra:
  recipe-maintainers:
    - maximlt
    - sbrunato
